#!/bin/sh -e
dir=$(cd "$(dirname "$0")" && pwd)
config_dir="$HOME/.config" && mkdir -p "$config_dir"
local_dir="$HOME/.local" && mkdir -p "$local_dir"

echo 'tmux'
ln -fs "$dir/tmux/tmux.conf" "$HOME/.tmux.conf"

echo 'git'
ln -Fs "$dir/git" "$config_dir/"

echo 'neovim'
rm -rf "$local_dir"/state/nvim "$local_dir"/share/nvim
ln -Fs "$dir/nvim" "$config_dir/"
ln -fs "$dir/../mac/spell" "$config_dir/nvim/"

echo 'editorconfig'
ln -Fs "$dir/editorconfig/.editorconfig" "$HOME/.editorconfig"
