#!/bin/sh -e
config_dir="$HOME/.config"
local_dir="$HOME/.local"

echo 'tmux'
rm -f "$HOME/.tmux.conf"

echo 'git'
rm -rf "$config_dir/git"

echo 'neovim'
rm -rf "$local_dir"/share/nvim "$local_dir"/state/nvim "$config_dir"/nvim

echo 'editorconfig'
rm -f "$HOME/.editorconfig"
