local o = vim.o

o.clipboard = "unnamedplus"
o.comments = "b:*,b:-,b:+,n:>:"
o.cursorline = true
o.formatoptions = "tcroqwanljB1"
o.ignorecase = true
o.laststatus = 1
o.linebreak = true
o.list = true
o.shadafile = vim.fn.stdpath("cache") .. "/shada"
o.shiftwidth = 2
o.smartcase = true
o.softtabstop = 2
o.swapfile = false
o.tabstop = 2
o.textwidth = 80
o.undofile = true
o.wildignorecase = true
o.wrap = false
o.writebackup = false
